FROM alpine:3.21

RUN apk update && apk add --no-cache \
    php82 \
    php82-fpm \
    php82-mysqli \
    php82-json \
    php82-openssl \
    php82-curl \
    php82-zlib \
    php82-xml \
    php82-phar \
    php82-intl \
    php82-dom \
    php82-xmlreader \
    php82-ctype \
    php82-session \
    php82-mbstring \
    php82-gd \
    php82-zip \
    php82-opcache

WORKDIR /var/www/html
RUN wget https://wordpress.org/latest.tar.gz && \
    tar xzf latest.tar.gz --strip-components=1 && \
    rm latest.tar.gz && \
    chown -R nobody:nobody /var/www/html

RUN sed -i 's/listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/' /etc/php82/php-fpm.d/www.conf && \
    sed -i 's/;listen.allowed_clients = 127.0.0.1/listen.allowed_clients = 0.0.0.0/' /etc/php82/php-fpm.d/www.conf

EXPOSE 9000

CMD ["php-fpm82", "-F"]
