FROM alpine:3.21

RUN apk update && apk add --no-cache \
    nginx \
    openssl

RUN mkdir -p /var/www/html \
	&& mkdir -p /etc/nginx/ssl

# 자체 서명 SSL 인증서 생성
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=KR/ST=Gyeongsangbuk-do/L=Gyeongsan/O=42GS/CN=inception"


COPY tools/nginx.conf /etc/nginx/nginx.conf
COPY tools/index.html	/var/www/html/index.html

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
